export type { IAccess } from './types/IAccess';
export type { IAddress, IBankDetails, IBase } from './types/IBase';
export type { IDepartment } from './types/IDepartment';
export type { IEnums } from './types/IEnums';
export type { IFile } from './types/IFile';
export type { ILaboratory } from './types/ILaboratory';
export type { IUser } from './types/IUser';
export type { IVerification } from './types/IVerification';
export type { ICustomer } from './types/ICustomer';
export type { IMaster, IParameters, IValidation } from './types/IMaster';
export type { ITestGroup, IAdditionalFields } from './types/ITestGroup';
export type { ISample } from './types/ISample';
export type { ISampleParameter } from './types/ISampleParameter';
export type { IReference } from './types/IReference';
export type { IPayment } from './types/IPayment';
export type { IPaymentDetails } from './types/IPaymentDetail';
