export type { IAccess } from './types/IAccess';
export type { IAddress, IBankDetails, IBase } from './types/IBase';
export type { IDepartment } from './types/IDepartment';
export type { IEnums } from './types/IEnums';
export type { IFile } from './types/IFile';
export type { ILaboratory } from './types/ILaboratory';
export type { IUser } from './types/IUser';
export type { IVerification } from './types/IVerification';
export type { ICustomer } from './types/ICustomer';
export type { IMaster, IParameters, IValidation } from './types/IMaster';
